components:
  schemas:
    User:
      description: Un usuario
      type: object
      properties:
        _id:
          $ref: "#/components/schemas/id"
        email:
          description: User email.
          type: string
          example: joe_doe@gmail.com
        password:
          $ref: "#/components/schemas/password"

    AuthUser:
      description: Service to auth a user.
      type: object
      properties:
        email:
          $ref: "#/components/schemas/User/properties/email"
        password:
          $ref: "#/components/schemas/User/properties/password"